### ISSUE TITLE
Hello, I encountered KeyError: '/home/lijing/ADNet-main/data/CHAOST2/chaos_MR_T2_normalized/image_21.nii.gz' when running train_abd_3D.sh

### ISSUE THREAD

**Issue by lijing-coder** [sha168/ADNet#2]
bash scripts/train_abd_3D.sh 
Namespace(EP1=False, all_slices=True, batch_size=1, bg_wt=0.1, data_root='/home/lijing/ADNet-main/data/CHAOST2', dataset='CHAOST2', fold=0, lr=0.001, lr_gamma=0.95, max_iterations=1000, max_slices=10, min_size=200, momentum=0.9, n_query=1, n_shot=1, n_sv=5000, n_way=1, save_root='/home/lijing/ADNet-main/results_abd_3d/train/fold0', seed=2021, steps=50000, t_loss_scaler=1.0, weight_decay=0.0005, workers=4)
Loading pre-trained weights!
  Training on images not in test fold: ['/chaos_MR_T2_normalized/image_10.nii.gz', '/chaos_MR_T2_normalized/image_13.nii.gz', '/chaos_MR_T2_normalized/image_15.nii.gz', '/chaos_MR_T2_normalized/image_19.nii.gz', '/chaos_MR_T2_normalized/image_20.nii.gz', '/chaos_MR_T2_normalized/image_21.nii.gz', '/chaos_MR_T2_normalized/image_22.nii.gz', '/chaos_MR_T2_normalized/image_31.nii.gz', '/chaos_MR_T2_normalized/image_32.nii.gz', '/chaos_MR_T2_normalized/image_33.nii.gz', '/chaos_MR_T2_normalized/image_34.nii.gz', '/chaos_MR_T2_normalized/image_36.nii.gz', '/chaos_MR_T2_normalized/image_37.nii.gz', '/chaos_MR_T2_normalized/image_38.nii.gz', '/chaos_MR_T2_normalized/image_39.nii.gz']
  Start training ...
Traceback (most recent call last):
  File "main_train_3D.py", line 178, in <module>
    main()
  File "main_train_3D.py", line 103, in main
    scheduler, epoch, args)
  File "main_train_3D.py", line 134, in train
    for i, sample in enumerate(train_loader):
  File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lijing/ADNet-main/dataloading/datasets_3D.py", line 213, in __getitem__
    img = self.images[self.image_dirs[pat_idx]]
KeyError: '/home/lijing/ADNet-main/data/CHAOST2/chaos_MR_T2_normalized/image_21.nii.gz'

The preprocessing  of the image follows ouyang, and it can be trained normally in the ouyang project, and the file generate_supervoxels.py can also be run.

**Comment by sha168** [comment]
Ok, so there is a key error saying that `self.images` does not have the key from `self.image_dirs[pat_idx] `. It is difficult to say for sure why this would be, but could it be that  `self.sprvxl_dirs` is empty? Because that should lead to a break in the loop in line 151 in `datasets_3D.py`, and thereby leaving `self.images` empty as well. I would start by checking that the path to the supervoxels is correct and that `self.sprvxl_dirs` is not empty. Let me know if that works.

Stine

**Comment by lijing-coder** [comment]
Thank you for your prompt response. Thank you for your perfect work. The above reason is that there is an error in my folder path. With your help, it has been resolved now, and there is another issue. Why does the model need to be deployed to the CPU? map_ Location='cpu ', error will be reported when I change to GPU.

**Comment by sha168** [comment]
Not entirely sure about this. Can you share the error message that you get? In my case, changing `map_location` to `cuda:0` works without problems.

Stine

**Comment by lijing-coder** [comment]
Thanks for your help. I have solve this issue.

**Comment by yaoyuanyuanyyy** [comment]
> bash scripts/train_abd_3D.sh Namespace(EP1=False, all_slices=True, batch_size=1, bg_wt=0.1, data_root='/home/lijing/ADNet-main/data/CHAOST2', dataset='CHAOST2', fold=0, lr=0.001, lr_gamma=0.95, max_iterations=1000, max_slices=10, min_size=200, momentum=0.9, n_query=1, n_shot=1, n_sv=5000, n_way=1, save_root='/home/lijing/ADNet-main/results_abd_3d/train/fold0', seed=2021, steps=50000, t_loss_scaler=1.0, weight_decay=0.0005, workers=4) Loading pre-trained weights! Training on images not in test fold: ['/chaos_MR_T2_normalized/image_10.nii.gz', '/chaos_MR_T2_normalized/image_13.nii.gz', '/chaos_MR_T2_normalized/image_15.nii.gz', '/chaos_MR_T2_normalized/image_19.nii.gz', '/chaos_MR_T2_normalized/image_20.nii.gz', '/chaos_MR_T2_normalized/image_21.nii.gz', '/chaos_MR_T2_normalized/image_22.nii.gz', '/chaos_MR_T2_normalized/image_31.nii.gz', '/chaos_MR_T2_normalized/image_32.nii.gz', '/chaos_MR_T2_normalized/image_33.nii.gz', '/chaos_MR_T2_normalized/image_34.nii.gz', '/chaos_MR_T2_normalized/image_36.nii.gz', '/chaos_MR_T2_normalized/image_37.nii.gz', '/chaos_MR_T2_normalized/image_38.nii.gz', '/chaos_MR_T2_normalized/image_39.nii.gz'] Start training ... Traceback (most recent call last): File "main_train_3D.py", line 178, in main() File "main_train_3D.py", line 103, in main scheduler, epoch, args) File "main_train_3D.py", line 134, in train for i, sample in enumerate(train_loader): File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in **next** data = self._next_data() File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data return self._process_data(data) File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data data.reraise() File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise raise exception KeyError: Caught KeyError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop data = fetcher.fetch(index) File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/lijing/ADNet-main/dataloading/datasets_3D.py", line 213, in **getitem** img = self.images[self.image_dirs[pat_idx]] KeyError: '/home/lijing/ADNet-main/data/CHAOST2/chaos_MR_T2_normalized/image_21.nii.gz'
> 
> The preprocessing of the image follows ouyang, and it can be trained normally in the ouyang project, and the file generate_supervoxels.py can also be run.

Hello, I also encountered the same problem. Can you tell me how to modify the path there?

**Comment by LiuSXU** [comment]
> > bash scripts/train_abd_3D.sh Namespace(EP1=False, all_slices=True, batch_size=1, bg_wt=0.1, data_root='/home/lijing/ADNet-main/data/CHAOST2', dataset='CHAOST2', fold=0, lr=0.001, lr_gamma=0.95, max_iterations=1000, max_slices=10, min_size=200, momentum=0.9, n_query=1, n_shot=1, n_sv=5000, n_way=1, save_root='/home/lijing/ADNet-main/results_abd_3d/train/fold0', seed=2021, steps=50000, t_loss_scaler=1.0, weight_decay=0.0005, workers=4) Loading pre-trained weights! Training on images not in test fold: ['/chaos_MR_T2_normalized/image_10.nii.gz', '/chaos_MR_T2_normalized/image_13.nii.gz', '/chaos_MR_T2_normalized/image_15.nii.gz', '/chaos_MR_T2_normalized/image_19.nii.gz', '/chaos_MR_T2_normalized/image_20.nii.gz', '/chaos_MR_T2_normalized/image_21.nii.gz', '/chaos_MR_T2_normalized/image_22.nii.gz', '/chaos_MR_T2_normalized/image_31.nii.gz', '/chaos_MR_T2_normalized/image_32.nii.gz', '/chaos_MR_T2_normalized/image_33.nii.gz', '/chaos_MR_T2_normalized/image_34.nii.gz', '/chaos_MR_T2_normalized/image_36.nii.gz', '/chaos_MR_T2_normalized/image_37.nii.gz', '/chaos_MR_T2_normalized/image_38.nii.gz', '/chaos_MR_T2_normalized/image_39.nii.gz'] Start training ... Traceback (most recent call last): File "main_train_3D.py", line 178, in main() File "main_train_3D.py", line 103, in main scheduler, epoch, args) File "main_train_3D.py", line 134, in train for i, sample in enumerate(train_loader): File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 628, in **next** data = self._next_data() File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data return self._process_data(data) File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data data.reraise() File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 543, in reraise raise exception KeyError: Caught KeyError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop data = fetcher.fetch(index) File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/lijing/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 58, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/lijing/ADNet-main/dataloading/datasets_3D.py", line 213, in **getitem** img = self.images[self.image_dirs[pat_idx]] KeyError: '/home/lijing/ADNet-main/data/CHAOST2/chaos_MR_T2_normalized/image_21.nii.gz'
> > The preprocessing of the image follows ouyang, and it can be trained normally in the ouyang project, and the file generate_supervoxels.py can also be run.
> 
> Hello, I also encountered the same problem. Can you tell me how to modify the path there?

Hello, have you solved this problem? I encountered the same problem too.
